---
docker_pkg_name: docker-engine
kernel_pkg_state: latest

cgroup_lite_pkg_state: latest

ssh_port: 22

# apt repository key signature
apt_key_sig: 58118E89F3A912897C070ADBF76221572C52609D
# Name of the apt repository for docker
apt_repository: deb https://apt.dockerproject.org/repo ubuntu-trusty main

# The following help expose a docker port or to add additional options when running docker
# The default is to not use any special options; see docker_opts
docker_host_ip: 0.0.0.0
docker_host_port: 2375
docker_opts: "-H unix:// -H tcp://{{ docker_host_ip }}:{{ docker_host_port }}"

# Want to export the docker host?  You'll need to uncomment the docker_host_ip, port, opts
export_docker_host: true
